wandb_version: 1

Machine:
  desc: null
  value: Main
Model:
  desc: null
  value: v19
_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    code_path: code/train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1665810796
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 35
      4: 3.10.4
      5: 0.12.16
      8:
      - 3
      - 5
model_save_name:
  desc: null
  value: test_run5
policy:
  desc: null
  value: MlpPolicy
