wandb_version: 1

Machine:
  desc: null
  value: Puget/Desktop/v18/2
Model:
  desc: null
  value: load-v16s
_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    code_path: code/load-train-model.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1665334678
    t:
      1:
      - 1
      - 55
      3:
      - 16
      - 35
      4: 3.10.4
      5: 0.12.16
      8:
      - 3
      - 5
load_model:
  desc: null
  value: models/test_run4/10000.zip
model_save_name:
  desc: null
  value: test_run4
policy:
  desc: null
  value: MlpPolicy
