wandb_version: 1

Machine:
  desc: null
  value: Main
Model:
  desc: null
  value: v19
_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    code_path: code/train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.0
    start_time: 1670893497.008194
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      - 35
      4: 3.9.0
      5: 0.13.6
      8:
      - 3
      - 5
model_save_name:
  desc: null
  value: trainingZerg
policy:
  desc: null
  value: MlpPolicy
